"""Common constants for aiotaipit tests."""
from __future__ import annotations

from aiotaipit.const import (
    DEFAULT_CLIENT_ID,
    DEFAULT_CLIENT_SECRET,
    GUEST_PASSWORD,
    GUEST_USERNAME,
)

TEST_CLIENT_ID = DEFAULT_CLIENT_ID
TEST_CLIENT_SECRET = DEFAULT_CLIENT_SECRET
TEST_USERNAME = GUEST_USERNAME
TEST_PASSWORD = GUEST_PASSWORD
